/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts;

/**
 *
 * @author wilda
 */
public class APKrestoran extends javax.swing.JFrame {

    /**
     * Creates new form APKrestoran
     */
    public APKrestoran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lalapanikan = new javax.swing.JCheckBox();
        lalapanayam = new javax.swing.JCheckBox();
        ayamkrispi = new javax.swing.JCheckBox();
        ayambakar = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargaikan = new javax.swing.JTextField();
        hargaayam = new javax.swing.JTextField();
        hargaayamkrispi = new javax.swing.JTextField();
        hargaayambakar = new javax.swing.JTextField();
        jumlahikan = new javax.swing.JTextField();
        jumlahayam = new javax.swing.JTextField();
        jumlahayamkrispi = new javax.swing.JTextField();
        jumlahayambakar = new javax.swing.JTextField();
        totalikan = new javax.swing.JTextField();
        totalayam = new javax.swing.JTextField();
        totalayamkrispi = new javax.swing.JTextField();
        totalayambakar = new javax.swing.JTextField();
        totalfull = new javax.swing.JTextField();
        diskon = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lalapanikan.setText("Lalapan ikan");
        lalapanikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanikanActionPerformed(evt);
            }
        });

        lalapanayam.setText("Lalapan Ayam");
        lalapanayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lalapanayamActionPerformed(evt);
            }
        });

        ayamkrispi.setText("Ayam Krispy");
        ayamkrispi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamkrispiActionPerformed(evt);
            }
        });

        ayambakar.setText("Ayam Bakar");
        ayambakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayambakarActionPerformed(evt);
            }
        });

        jLabel1.setText("Aplikasi Restoran");

        jLabel2.setText("Menu Makanan");

        jLabel3.setText("Harga");

        jLabel4.setText("Jumlah");

        jLabel5.setText("Sub total");

        hargaikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaikan.setText("0");

        hargaayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayam.setText("0");

        hargaayamkrispi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayamkrispi.setText("0");

        hargaayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        hargaayambakar.setText("0");

        jumlahikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahikan.setText("0");

        jumlahayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayam.setText("0");

        jumlahayamkrispi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayamkrispi.setText("0");

        jumlahayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jumlahayambakar.setText("0");

        totalikan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalikan.setText("0");

        totalayam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayam.setText("0");

        totalayamkrispi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayamkrispi.setText("0");

        totalayambakar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalayambakar.setText("0");

        totalfull.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalfull.setText("0");

        diskon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        diskon.setText("0");

        bayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bayar.setText("0");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jLabel6.setText("Total");

        jLabel7.setText("Diskon");

        jLabel8.setText("Total Bayar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ayambakar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hargaayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ayamkrispi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hargaayamkrispi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lalapanayam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hargaayam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lalapanikan)
                                    .addGap(56, 56, 56)
                                    .addComponent(hargaikan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(hitung))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahikan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlahayam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlahayamkrispi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlahayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bayar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(diskon)
                            .addComponent(totalfull)
                            .addComponent(totalikan)
                            .addComponent(totalayam)
                            .addComponent(totalayamkrispi)
                            .addComponent(totalayambakar))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalapanikan)
                    .addComponent(hargaikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalapanayam)
                    .addComponent(hargaayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayamkrispi)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hargaayamkrispi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jumlahayamkrispi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalayamkrispi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayambakar)
                    .addComponent(hargaayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalayambakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalfull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitung)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lalapanikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanikanActionPerformed
        // TODO add your handling code here:
         if (lalapanikan.isSelected()){
            hargaikan.setEnabled(true);
            jumlahikan.setEnabled(true);           
            totalikan.setEnabled(true);
        }else{
            hargaikan.setEnabled(false);
            jumlahikan.setEnabled(false);
            totalikan.setEnabled(false);
        }

    }//GEN-LAST:event_lalapanikanActionPerformed

    private void lalapanayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lalapanayamActionPerformed
        // TODO add your handling code here:
          if (lalapanayam.isSelected()){
            hargaayam.setEnabled(true);
            jumlahayam.setEnabled(true);           
            totalayam.setEnabled(true);
        }else{
            hargaayam.setEnabled(false);
            jumlahayam.setEnabled(false);
            totalayam.setEnabled(false);
        }

    }//GEN-LAST:event_lalapanayamActionPerformed

    private void ayamkrispiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamkrispiActionPerformed
        // TODO add your handling code here:
         if (ayamkrispi.isSelected()){
            hargaayamkrispi.setEnabled(true);
            jumlahayamkrispi.setEnabled(true);           
            totalayamkrispi.setEnabled(true);
        }else{
            hargaayamkrispi.setEnabled(false);
            jumlahayamkrispi.setEnabled(false);
            totalayamkrispi.setEnabled(false);
        }

    }//GEN-LAST:event_ayamkrispiActionPerformed

    private void ayambakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayambakarActionPerformed
        // TODO add your handling code here:
           if (ayambakar.isSelected()){
            hargaayambakar.setEnabled(true);
            jumlahayambakar.setEnabled(true);           
            totalayambakar.setEnabled(true);
        }else{
            hargaayambakar.setEnabled(false);
            jumlahayambakar.setEnabled(false);
            totalayambakar.setEnabled(false);
        }

    }//GEN-LAST:event_ayambakarActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
           int harga = Integer.parseInt(hargaikan.getText());
        int jumlah = Integer.parseInt(jumlahikan.getText());
        totalikan.setText(Integer.toString(jumlah * harga)); //Menghitung subTotal harga ikan
        
        int harga1 = Integer.parseInt(hargaayam.getText());
        int jumlah1= Integer.parseInt(jumlahayam.getText());
        totalayam.setText(Integer.toString(harga1 * jumlah1));//menghitung subTotal harga ayam
        
        int harga2 = Integer.parseInt(hargaayamkrispi.getText());
        int jumlah2 = Integer.parseInt(jumlahayamkrispi.getText());
        totalayamkrispi.setText(Integer.toString(harga2 * jumlah2)); //Menghitung subTotal harga ayam krispi
        
        int harga3 = Integer.parseInt(hargaayambakar.getText());
        int jumlah3 = Integer.parseInt(jumlahayambakar.getText());
        totalayambakar.setText(Integer.toString(harga3 * jumlah3)); //Menghitung subTotal harga ayam bakar
        
        // Menghitung harga total, diskon dan total bayar
        int Total1 = Integer.parseInt(totalikan.getText());
        int Total2 = Integer.parseInt(totalayam.getText());
        int Total3 = Integer.parseInt(totalayamkrispi.getText());
        int Total4 = Integer.parseInt(totalayambakar.getText());
        int Full = Total1 + Total2 + Total3 + Total4;
        totalfull.setText("Rp." + Full + ",00");
        if (Full > 250000){
            diskon.setText("20%");
            Full = Full-(Full * 20/100);
            bayar.setText("Rp." + Full + ",00");
        }else if (Full > 150000){
            diskon.setText("10%");
            Full = Full-(Full*10/100);
            bayar.setText("Rp." + Full + ",00");
        }else{
            bayar.setText("Rp."+Full+",00");
        }

    }//GEN-LAST:event_hitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APKrestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APKrestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APKrestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APKrestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APKrestoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayambakar;
    private javax.swing.JCheckBox ayamkrispi;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField hargaayam;
    private javax.swing.JTextField hargaayambakar;
    private javax.swing.JTextField hargaayamkrispi;
    private javax.swing.JTextField hargaikan;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlahayam;
    private javax.swing.JTextField jumlahayambakar;
    private javax.swing.JTextField jumlahayamkrispi;
    private javax.swing.JTextField jumlahikan;
    private javax.swing.JCheckBox lalapanayam;
    private javax.swing.JCheckBox lalapanikan;
    private javax.swing.JTextField totalayam;
    private javax.swing.JTextField totalayambakar;
    private javax.swing.JTextField totalayamkrispi;
    private javax.swing.JTextField totalfull;
    private javax.swing.JTextField totalikan;
    // End of variables declaration//GEN-END:variables
}
